---
http_interactions:
- request:
    method: delete
    uri: http://localhost:8988/marmotta/context/http://localhost:8988/linked-data-fragments-test
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Hurley v0.2
      Accept:
      - application/ld+json
      Content-Type:
      - application/ld+json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Length:
      - '0'
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Sat, 04 Feb 2017 04:22:13 GMT
recorded_with: VCR 3.0.3
