---
http_interactions:
- request:
    method: delete
    uri: http://localhost:8988/blazegraph/sparql
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Host:
      - localhost:8988
      Connection:
      - keep-alive
      Keep-Alive:
      - 30
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - application/xml;charset=ISO-8859-1
      Content-Length:
      - '59'
    body:
      encoding: UTF-8
      string: <?xml version="1.0"?><data modified="0" milliseconds="20"/>
    http_version: 
  recorded_at: Sat, 04 Feb 2017 04:22:07 GMT
recorded_with: VCR 3.0.3
